title: Putta Bhanu Prakash
theme: minima
author: Putta Bhanu Prakash
email: bhanu.putta1999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a free-spirited and adventurous person. I believe in living 
  life to the fullest and don’t let barriers of customs and language 
  stop me from having great experiences. I keep learning new stuff 
  every day. I love inspiring people with my work and sincerity.
  

# social links
twitter_username: theharrypotterb # DO NOT include the @ character, or else the build will fail!
github_username:  theharrypotter1999 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
